'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const cardUi = require('./public/card-ui');

assert.equal(cardUi.noteLabel('阅读', '句子对照'), '错因（选填）');
assert.equal(cardUi.noteLabel('听力', '句子对照'), '错因（选填）');
assert.equal(cardUi.noteLabel('口语', '句子对照'), '错因（选填）');
assert.equal(cardUi.noteLabel('阅读', '生词'), '备注（选填）');
console.log('✓ note 动态标签断言通过：任意技能+句子对照均显示“错因（选填）”，其他类型显示“备注（选填）”');
const appSource = fs.readFileSync(require.resolve('./public/app.js'), 'utf8');
const serviceWorkerSource = fs.readFileSync(require.resolve('./public/sw.js'), 'utf8');
assert.match(appSource, /id="show-writing-form"/);
assert.match(appSource, /id="writing-content"[\s\S]*maxlength="5000"/);
assert.match(appSource, /id="cancel-writing"/);
assert.match(appSource, /if \(!content\)[\s\S]*return;/);
assert.match(appSource, /JSON\.stringify\(\{ content \}\)/);
assert.match(appSource, /weekly\.writing\.records\.map/);
console.log('✓ 写作录入 UI 合同断言通过：展开 textarea、取消、空内容拦截、携带 content 提交及周记录渲染均存在');
assert.match(appSource, /name="front_audio"[\s\S]*maxlength="5000"/);
assert.equal((appSource.match(/escapeHtml\(card\?\.front_audio \|\| ''\)/g) || []).length, 1);
assert.match(appSource, /<h3>\$\{escapeHtml\(card\.front\)\}<\/h3>\$\{speech\.buttonHtml\(speech\.frontText\(card\)/);
assert.match(appSource, /<h2>\$\{escapeHtml\(card\.front\)\}<\/h2>\$\{speech\.buttonHtml\(speech\.frontText\(card\)/);
assert.doesNotMatch(appSource, /<(?:h2|h3|p)[^>]*>\$\{escapeHtml\(card\??\.front_audio/);
console.log('✓ front_audio 可见渲染合同断言通过：只在录入/编辑 textarea 回显，卡片库与复习正面只渲染 front');
assert.match(appSource, /name="review_mode"[\s\S]*value="spelling"/);
assert.match(appSource, /payload\.review_mode = form\.has\('review_mode'\) \? 'spelling' : 'flip'/);
assert.match(appSource, /function renderSpellingReview/);
assert.match(appSource, /speech\.buttonHtml\(card\.spelling_audio, '正确拼写', \{ base64: true \}\)/);
assert.match(appSource, /`\/api\/review\/\$\{card\.id\}\/spelling`/);
const spellingRenderSource = appSource.slice(appSource.indexOf('function renderSpellingReview'), appSource.indexOf('async function renderProgress'));
assert.doesNotMatch(spellingRenderSource, /escapeHtml\(card\.back\)/);
console.log('✓ 拼写模式 UI 合同断言通过：表单开关、专用复习表单、背面朗读及提交前不渲染back均存在');
assert.match(appSource, /今天已经清空啦[\s\S]*data-start-practice="all"[\s\S]*data-start-practice="today"/);
assert.match(appSource, /data-practice-card="\$\{card\.id\}"/);
assert.match(appSource, /function renderPractice/);
assert.match(appSource, /state\.reviewKind === 'formal'[\s\S]*api\(`\/api\/review\/\$\{card\.id\}`/);
assert.match(appSource, /`\/api\/practice\/cards\/\$\{card\.id\}\/spelling`/);
assert.match(appSource, /本轮只做自测，不改变箱位和日期/);
console.log('✓ 自由/单卡练习 UI 合同通过：清空入口、范围选择、卡片库点击和拼写只读提交路径均存在');
assert.match(appSource, /function renderListeningOverview/);
assert.match(appSource, /function renderListeningPractice/);
assert.match(appSource, /<audio controls preload="metadata"/);
assert.match(appSource, /listeningTranscriptHtml\(section\.transcript_segments\)/);
assert.match(appSource, /data-answer-number=/);
assert.match(appSource, /const answers = Object\.fromEntries/);
assert.match(appSource, /showListeningGrading\(result\)/);
assert.doesNotMatch(appSource, /name="score_correct"/);
assert.match(appSource, /data-reveal="transcript-panel"/);
assert.match(appSource, /data-reveal="answer-panel"/);
assert.match(appSource, /name="check_retention"/);
assert.match(serviceWorkerSource, /pathname\.startsWith\('\/listening-audio\/'\)/);
console.log('✓ 听力练习 UI 合同断言通过：默认展示原文挖空、提交answers后原地展示自动判分，完整原文/答案仍可隐藏查看，5项表单保留');
console.log('全部字段标签 UI 规则测试通过。');
